azure:
  volumeHandle: /subscriptions/my-subscription/resourceGroups/my-group/providers/Microsoft.Compute/disks/mediawiki-default
  region: westus2

  mariadb:
    enabled: false

mediawiki:
  mediawikiName: Default Mediawiki
  mediawikiHost: default.wiki.example.com
  mediawikiEmail: admin@example.com
  mediawikiUser: admin
  mediawikiPassword: XXXXXXXX

  mariadb:
    enabled: false

  externalDatabase:
    host: default.database.example.com
    database: mediawiki_default
    user: user@example.com
    password: XXXXXXXX

  smtpHost: mail.example.com
  smtpPort: 465
  smtpUser: system@example.com
  smtpPassword: XXXXXXXX

  persistence:
    existingClaim: mediawiki-default

  allowEmptyPassword: "no"

  service:
    type: ClusterIP

  ingress:
    enabled: true
    tls: true
    hostname: default.example.com
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      cert-manager.io/acme-challenge-type: http01
  
  command: ["bash", "/opt/local/bin/init.sh"]
  args: ["/opt/bitnami/scripts/apache/run.sh"]

  extraEnvVars:
    - name: BITNAMI_DEBUG
      value: "true"
    - name: MEDIAWIKI_ENABLE_HTTPS
      value: "yes"
    - name: PHP_ENABLE_OPCACHE
      value: "yes"
    - name: MYSQL_CLIENT_ENABLE_SSL
      value: "yes"
    # - name: MYSQL_CLIENT_SSL_CA_FILE
    #   value: /opt/local/etc/ssl-ca.crt.pem

  extraVolumeMounts:
    - name: php-conf
      mountPath: /opt/bitnami/php/etc/conf.d
    - name: local
      mountPath: /opt/local/bin
    - name: localsettings
      mountPath: /opt/local/etc/LocalSettings.php

  extraVolumes:
    - name: php-conf
      configMap:
        name: '{{ template "common.names.fullname" . }}--local'
        items:
          - key: custom.ini
            path: custom.ini
    - name: local
      configMap:
        name: '{{ template "common.names.fullname" . }}--local'
        defaultMode: 0777
        items:
          - key: init.sh
            path: init.sh
    - name: localsettings
      secret:
        secretName: '{{ template "common.names.fullname" . }}--local'