apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}--local-init
data:
  get_mediawiki_extensions.sh: |
    #!/bin/bash

    cd /bitnami/mediawiki/extensions

    EXTENSIONS=(
        'AbuseFilter'
        'CategoryTree'
        'Cite'
        'CodeEditor'
        'Gadgets'
        'Graph'
        'ImageMap'
        'InputBox'
        'Interwiki'
        'JsonConfig'
        'Math'
        'MultimediaViewer'
        'Nuke'
        'OATHAuth'
        'PageImages'
        'ParserFunctions'
        'PdfHandler'
        'Poem'
        'Popups'
        'RenameUser'
        'ReplaceText'
        'Scribunto'
        'SecureLinkFixer'
        'SyntaxHighlight'
        'TemplateData'
        'TextExtracts'
        'TitleBlacklist'
        'TwoColConflict'
        'VisualEditor'
        'WikiEditor'
    )

    BRANCH="REL1_38"

    echo_extension_url () {
        NAME="$1"
        echo "https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/${NAME}/+archive/refs/heads/${BRANCH}.tar.gz"
    }

    get_extension() {
        NAME="$1"
        URL="$(echo_extension_url "$NAME")"
        if [ ! -d "$NAME" ]
        then
            curl -o "${NAME}.tar.gz" "$URL" && \
            mkdir "$NAME" && \
            tar -xf "${NAME}.tar.gz" -C "$NAME" && \
            rm "${NAME}.tar.gz"
        else
            echo '* exists'
        fi
    }

    for i in "${EXTENSIONS[@]}"
    do
        echo Downloading "'$i'"
        get_extension "$i"
    done