apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}--local
data:
  init.sh: |
    #!/bin/bash

    cp /opt/local/etc/LocalSettings.php /bitnami/mediawiki/

    exec /opt/bitnami/scripts/mediawiki/entrypoint.sh "$@"
  custom.ini: |
    ; php.ini overrides

    ; Increase upload size
    upload_max_filesize = 100M
    post_max_size = 100M

    ; Extensions

    extension = apcu
    extension = imagick