apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}--astral
data:
  init.sh: |
    #!/bin/bash

    cp /opt/astral/LocalSettings.php /bitnami/mediawiki/

    exec /opt/bitnami/scripts/mediawiki/entrypoint.sh "$@"
  custom.ini: |
    ; Extensions

    extension = apcu
    extension = imagick