apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mediawiki.persistence.existingClaim }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  volumeName: {{ .Values.mediawiki.persistence.existingClaim }}
  resources:
    requests:
      storage: 32Gi