apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}--local
stringData:
  ssl-ca.crt.pem: |
{{ .Files.Get "certs/BaltimoreCyberTrustRoot.crt.pem" | indent 4 }}
  LocalSettings.php: |
    {{- include "astral.mediawiki.localsettings" . | indent 4 }}